municipalidad/app/__init__.py
import os
from flask import Flask, render_template, Blueprint, redirect, url_for
from .modelo_base import db
from .helpers import (
    register_commands, login_manager, add_time, get_shell, migrate
)
from .routes import bp as bp_home
from .auth import bp as bp_auth
from .preocupacionales import bp as bp_preocupacionales


def create_app(instance_path):
    # create and configure the app
    app = Flask(__name__,
        instance_path=instance_path,
        instance_relative_config=True)

    app.config.from_pyfile('config.py')

    # ensure the instance folder exists
    try:
        os.makedirs(app.instance_path)
    except OSError:
        pass

    # initializations
    db.init_app(app) # db
    register_commands(app) # cli commands
    get_shell(app) # flask shell
    login_manager.init_app(app) # flask-login
    migrate.init_app(app, db)

    # jinja filters
    app.jinja_env.filters['add_time'] = add_time

    # route blueprints
    app.register_blueprint(bp_home)
    app.register_blueprint(bp_auth)
    app.register_blueprint(bp_preocupacionales)

    @app.errorhandler(404)
    def not_found(error):
        return render_template('error.html',
            mensaje=("La página buscada no existe. Si cree que esto es un "
            "error contáctese con el administrador del sistema.")), 404

    @app.errorhandler(403)
    def forbidden(error):
        return render_template('error.html',
            mensaje='No tiene permiso para ver esta página.'), 403

    return app

municipalidad/app/preocupacionales/__init__.py
from flask import (
    Blueprint, render_template, url_for, redirect, flash, current_app, abort,
    request
)
from flask_login import login_required
from sqlalchemy import func
from sqlalchemy.exc import IntegrityError
from datetime import datetime
from .modelos import db, Agente, Reparticion, Turno, Calendario
from .formularios import FormularioAgente, FormularioEditarAgente
from app.auth.modelos import Permiso
from app.auth.decorators import permission_required

bp = Blueprint('preocupacionales', __name__, url_prefix='/preocupacionales')


@bp.route('/')
@login_required
def index():
    return redirect(url_for('preocupacionales.lista'))


@bp.route('/nuevo_agente/', methods=('GET', 'POST'))
@login_required
@permission_required(Permiso.CREAR_AGENTE)
def nuevo_agente():
    form = FormularioAgente()
    if form.validate_on_submit():
        nuevo_agente = Agente.con_turnos()
        form.populate_obj(nuevo_agente)
        db.session.add(nuevo_agente)
        try:
            db.session.commit()
            flash('Agente creado', "border text-center text-success mb-3")
            return redirect(url_for('home.exito', id=nuevo_agente.id))
        except IntegrityError as e:
            db.session.rollback()
            agente_existente = Agente.query.filter_by(
                dni=nuevo_agente.dni).first()
            if agente_existente is not None:
                error = 'Ya existe un agente con el DNI {} ({} {})'.format(
                    nuevo_agente.dni, agente_existente.nombre,
                    agente_existente.apellido
                )
            else:
                error = e
            flash(error, 'border text-center text-danger mb-3')
    return render_template('preocupacionales/nuevo_agente.html', form=form)


@bp.route('/agente/<int:id>/', methods=('GET', 'POST'))
@login_required
@permission_required(Permiso.EDITAR_AGENTE)
def editar_agente(id):
    agente = Agente.query.filter_by(id=id).first()

    if agente is None:
        abort(404)

    form = FormularioEditarAgente(obj=agente)
    if request.method == 'POST':
        if request.form['action'] == 'guardar':
            if form.validate():
                db.session.add(agente)
                form.populate_obj(agente, edicion=True)
                try:
                    db.session.commit()
                    flash('Los cambios fueron guardados',
                        'border text-center text-success mb-3')
                except IntegrityError as e:
                    db.session.rollback()
                    agente_existente = Agente.query.filter_by(
                        dni=form.dni.data).first()
                    if agente_existente is not None:
                        error = 'Ya existe un agente con el DNI {} ({} {})' \
                            .format(form.dni.data, agente_existente.nombre,
                                agente_existente.apellido)
                        form.dni.errors.append("DNI original: {}".format(
                            agente.dni
                        ))
                    else:
                        error = e
                    flash(error, 'border text-center text-danger mb-3')
        elif request.form['action'] == 'eliminar':
            db.session.delete(agente)
            try:
                db.session.commit()
                flash('Agente eliminado.',
                    'border text-center text-success mb-3')
                return redirect(url_for('preocupacionales.lista'))
            except:
                flash('error sin identificar')

    return render_template('preocupacionales/editar_agente.html', form=form,
        id=id)


@bp.route('/listado')
@bp.route('/listado/<any("completo","pendientes_psi", "pendientes_med"):tipo_listado>')
@login_required
@permission_required(Permiso.VER_AGENTES)
def lista(tipo_listado='completo'):
    if tipo_listado == 'completo':
        agentes = Agente.query.all()
    else:
        from .vistas import AgentesPendientes
        agentes = AgentesPendientes.query.filter(
            AgentesPendientes.tipo_turno == (
                1 if tipo_listado == 'pendientes_psi' else 2
            )
        )
    return render_template('preocupacionales/lista.html', agentes=agentes,
    tipo_listado=tipo_listado)


@bp.route('/cedula/<any("completa","psi","med"):tipo_cedula>/<int:id_agente>/')
@login_required
@permission_required(Permiso.EDITAR_AGENTE)
def cedula(tipo_cedula, id_agente):
    agente = Agente.query.filter_by(id=id_agente).first()

    if agente is None:
        abort(404)

    turno_psi = agente.psi_2.fecha or agente.psi_1.fecha
    turno_med = agente.med_2.fecha or agente.med_1.fecha

    error = None
    if tipo_cedula == 'completa':
        if turno_psi is None or turno_med is None:
            error = ('Falta alguno de los turnos para generar '
            'una cédula completa.')
    elif tipo_cedula == 'psi':
        if turno_psi is None:
            error = ('No puede imprimirse la cédula ya que no hay turno de '
            'preocupacional psicológico asignado para este agente.')
    elif tipo_cedula == 'med':
        if turno_med is None:
            error = ('No puede imprimirse la cédula ya que no hay turnos de '
            'preocupacional clínico asignado para este agente.')
    if error:
        return render_template('error.html', mensaje=error)
    return render_template('preocupacionales/cedula.html', agente=agente,
        tipo_cedula=tipo_cedula, fecha=datetime.now().strftime('%d/%m/%Y'))


@bp.route('/calendario/')
@bp.route('/calendario/<any("psi", "med"):tipo>/')
@login_required
@permission_required(Permiso.VER_AGENTES)
def calendario(tipo='psi'):
    """Vista de calendario

    Esta ruta permite visualizar los turnos en formato de calendario.
    El template incluye botones para elegir turnos psicológicos o médicos.
    La query trae el turno del número más alto de cada tipo para cada agente;
    de este modo si el agente tiene dos turnos asignados, sólo se mostrará el
    segundo, ya que se entiende que si le fue asignado un segundo turno es
    porque no pudo hacerse presente en el primero y, por ende, ese espacio
    queda liberado.
    """
    # obtenemos los turnos, esta consulta equivale a:
    # select id, tipo, max(numero), fecha from turnos where fecha is not null
    # and tipo = (1 o 2 segun psi o med) group by agente_id, tipo
    id_turnos = db.session.query(
        Turno.agente_id, Turno.tipo, func.max(Turno.numero)
    ).filter(
        Turno.fecha != None, Turno.tipo == (1 if tipo == 'psi' else 2)
    ).group_by(Turno.agente_id, Turno.tipo).with_entities(Turno.id).all()
    calendarios = Calendario.query.filter_by(
        tipo = (1 if tipo == 'psi' else 2)).all()
    # query equivalente:
    # select * from turnos where id in (id_turnos)
    turnos = Turno.query.filter(Turno.id.in_([id[0] for id in id_turnos]))
    return render_template('preocupacionales/calendario.html', turnos=turnos,
        tipo=tipo, calendarios=calendarios)

municipalidad/app/routes.py
from flask import Blueprint, redirect, url_for, render_template
from flask_login import login_required

bp = Blueprint('home', __name__, url_prefix='')

@bp.route('/')
@login_required
def index():
    return redirect(url_for('preocupacionales.lista'))

@bp.route('/exito/<int:id>')
def exito(id): # esta es una vista de prueba, hay que eliminarla
    return render_template('exito.html', id=id)

municipalidad/app/templates/base.html
<!DOCTYPE html>
<html lang="es">
<head>
  {% block head %}
  <title>APP</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- CSS -->
  <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.png') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/css/bootstrap.min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='fontawesome/css/all.min.css') }}">

  <!-- JavaScript -->
  <!-- Bootstrap y requeridos -->
  <script src="{{ url_for('static', filename='bootstrap/js/jquery-3.3.1.min.js')}}"></script>
  <script src="{{ url_for('static', filename='bootstrap/js/popper.min.js')}}"></script>
  <script src="{{ url_for('static', filename='bootstrap/js/bootstrap.min.js')}}"></script>
  <style media="screen">
  @media only screen and (max-width: 416px) {
    .pt-5 {
      padding-top: 5rem !important;
    }
  }
  </style>
  {% endblock %}
  {% block extra_head %}{% endblock %}
</head>
<body class="pt-5">
  <!-- Nav -->
  <nav class="navbar fixed-top navbar-expand-lg navbar-dark bg-primary mb-5" style="">
    <a class="navbar-brand" href="{{ url_for('home.index') }}">Dirección de Medicina Ocupacional</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbar">
      <ul class="navbar-nav mr-auto d-flex justify-content-between" style="min-width: 100%">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" href="#">Agentes</a>
          <div class="dropdown-menu">
            <a class="dropdown-item" href="{{ url_for('preocupacionales.lista') }}">Listado</a>
            <a class="dropdown-item" href="{{ url_for('preocupacionales.nuevo_agente') }}">Nuevo Agente</a>
            <a class="dropdown-item" href="{{ url_for('preocupacionales.calendario') }}">Calendario</a>
          </div>
        </li>
        {% if current_user.is_anonymous %}
        <a class="nav-link active" href="{{ url_for('auth.login') }}">Ingresar</a>
        {% else %}
        <a class="nav-link active" href="{{ url_for('auth.logout') }}">Salir</a>
        {% endif %}
    </div>
</nav>
<!-- Fin nav -->

<!-- Contenedor Bootstrap -->
<div class="container-fluid pt-3">
  {% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
  <div class="flashes">
    {% for category, message in messages %}
    <div class="{{ category }}">{{ message }}</div>
    {% endfor %}
  </div>
  {% endif %}
  {% endwith %}
  {% block contenido %}{% endblock %}
</div>
<!-- Fin contenedor Bootstrap -->
</body>
</html>

municipalidad/app/templates/error.html
{% extends "base.html" %}
{% block contenido %}
{{ mensaje }}
{% endblock %}

municipalidad/app/templates/exito.html
{% extends "base.html" %}
{% block contenido %}
Volver a nuevo agente haciendo clic <a href="{{ url_for('preocupacionales.editar_agente', id=id)}}">aquí</a>
{% endblock %}

municipalidad/app/templates/preocupacionales/calendario.html
{% extends "base.html" %}
{% block extra_head %}
<link rel="stylesheet" href="{{ url_for('static', filename='fullcalendar/css/fullcalendar.min.css') }}">
<link rel="stylesheet" href="{{ url_for('static', filename='fullcalendar/css/fullcalendar.print.min.css') }}" media="print">
<script src="{{ url_for('static', filename='moment/js/moment.min.js')}}"></script>
<script src="{{ url_for('static', filename='moment/js/locales.js')}}"></script>
<script src="{{ url_for('static', filename='fullcalendar/js/fullcalendar.min.js') }}"></script>
<script src="{{ url_for('static', filename='fullcalendar/js/locale/es.js') }}"></script>
<script type="text/javascript" class="init">
  $(document).ready(function() {
    $('#calendar').fullCalendar({
      weekends: false, // will hide Saturdays and Sundays
      defaultView: 'agendaWeek',
      timezone: 'America/Argentina/Buenos_Aires',
      locale: 'es',
      eventRender: function(eventObj, $el) {
        $el.popover({
          title: eventObj.title,
          content: eventObj.description,
          trigger: 'hover',
          placement: 'top',
          container: 'body'
        });
      },
      eventClick : function(event) {
        if (event.url) {
          window.open(event.url, "_blank");
          return false;
        }
      },
      events: [
      {% for turno in turnos %}{
        title: '{{ turno.agente.nombre }} {{ turno.agente.apellido }} DNI: {{ turno.agente.dni }}',
        start: '{{ turno.fecha }}',
        end: '{{ turno.fecha|add_time(minutes=30 if tipo == 'psi' else 10) }}',
        description: '{{ turno.calendario.etiqueta }}',
        color: '{{ turno.calendario.color }}',
        url: '{{ url_for('preocupacionales.editar_agente', id=turno.agente.id) }}',
        allDay: false
      }{% if not loop.last %},
      {% endif %}{% endfor %}
      ],
      height: 650,
      navLinks: true,
      weekNumbers: true,
      header: {
        left:   'title',
        center: '',
        right:  'today month,agendaWeek,agendaDay,day,list prevYear,prev,next,nextYear'
      },
      fixedWeekCount: false,
      minTime: '{{ '07' if tipo == 'med' else '08' }}:00:00',
      maxTime: '{{ '10' if tipo == 'med' else '17' }}:00:00',
      slotLabelInterval: { minutes: {{ '10' if tipo == 'med' else '30' }} },
      slotDuration: '00:{{ '10' if tipo == 'med' else '30' }}:00',
      slotLabelFormat: 'H:mm',
      eventLimit: 4,
      views: {
        agendaWeek : {
          columnHeaderFormat: 'DD/MM',
          titleFormat: 'DD [de] MMMM [de] YYYY'
        }
      },
      allDaySlot: false,
      nowIndicator: true,
      themeSystem: 'bootstrap4',
      bootstrapFontAwesome: {
        close: 'fas fa-times',
        prev: 'fas fa-chevron-left',
        next: 'fas fa-chevron-right',
        prevYear: 'fas fa-angle-double-left',
        nextYear: 'fas fa-angle-double-right'
      }
    });
  } );
</script>
{% endblock %}
{% block contenido %}
<div class="row">
  <div class="col-md-2">
    <div class="pt-5">
      <div class="border rounded bg-light p-2 mb-2">
        <div class="h5 text-center pl-1">Calendarios</div>
        <div class="btn-group-vertical btn-block">
          <a class="btn btn-primary {{ 'active' if tipo == 'psi' else ''}}" href="{{ url_for('preocupacionales.calendario', tipo='psi') }}">Turnos psicológicos</a>
          <a class="btn btn-primary {{ 'active' if tipo == 'med' else ''}}" href="{{ url_for('preocupacionales.calendario', tipo='med') }}">Turnos médicos</a>
        </div>
      </div>
      <button id="buttonImprimir" class="btn btn-block btn-primary hidden-print"><i class="fas pr-1 fa-print"></i>Imprimir</button>
      <div class="pt-3">
        <div class="border rounded bg-light p-2 mb-2">
          <div class="ml-2">
            <h5 class="pb-1">Referencias</h5>
            {% for calendario in calendarios %}
            <i class="fas fa-circle pr-1" style="color: {{ calendario.color }}"></i>{{ calendario.etiqueta }}<br>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-10">
    <div id="calendar"></div>
  </div>
</div>
{% endblock %}

municipalidad/app/templates/preocupacionales/lista.html
{% extends "base.html" %}
{% block extra_head %}

<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='datatables/datatables.min.css')}}"/>
<script type="text/javascript" src="{{ url_for('static', filename='datatables/datatables.min.js')}}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='datatables/accent-neutralise.min.js')}}"></script>

<script type="text/javascript" class="init">
  $(document).ready(function() {
    $('#listado').DataTable( {
      responsive: true,
      "dom": '<"row justify-content-end"<"col-1"l><"col-8"p><"col-3"f>>ti',
      initComplete: function () {
        this.api().columns([6, 7]).every( function () {
          var column = this;
          var select = $('<select class="form-control d-inline-block p-0" style="height:auto; width: auto"><option value="">Todos</option></select>')
          .appendTo( $(column.header()) )
          .on( 'change', function () {
            var val = $.fn.dataTable.util.escapeRegex(
            $(this).val()
            );

            column
            .search( val ? '^'+val+'$' : '', true, false )
            .draw();
          } );

          column.data().unique().sort().each( function ( d, j ) {
            select.append( '<option value="'+d+'">'+d+'</option>' )
          } );
        } );
      }
    } );
    var table = $('#listado').dataTable();

    // Remove accented character from search input as well
    $('#listado_filter input').keyup( function () {
      table
      .api()
      .search(
      jQuery.fn.DataTable.ext.type.search.string( this.value )
      )
      .draw()
    } );
  } );
</script>
{% endblock %}
{% block contenido %}
<div class="row mt-3">
  <div class="col-6">
    <a href="{{ url_for('preocupacionales.nuevo_agente') }}" class="btn btn-primary"><i class="fas fa-user-plus"></i> Nuevo agente</a>
    <a href="#" class="btn btn-primary"><i class="fas fa-file-export"></i> Exportar listado</a>
  </div>
  <div class="col-6">
    <div class="row justify-content-end">
      <div class="col-md-auto">
        <div class="btn-group btn-block">
          <a href="{{ url_for('preocupacionales.lista', tipo_listado='completo') }}" class="btn btn-secondary {{ 'active' if tipo_listado == 'completo' else ''}}">Todos</a>
          <a href="{{ url_for('preocupacionales.lista', tipo_listado='pendientes_psi') }}" class="btn btn-secondary {{ 'active' if tipo_listado == 'pendientes_psi' else ''}}">Sin turno psicológico</a>
          <a href="{{ url_for('preocupacionales.lista', tipo_listado='pendientes_med') }}" class="btn btn-secondary {{ 'active' if tipo_listado == 'pendientes_med' else ''}}">Sin turno médico</a>
        </div>
      </div>
    </div>

  </div>
</div>
<div class="mt-3">
  <table id="listado" class="table text-center table-striped table-bordered table-hover table-sm" width="100%">
    <thead class="thead-light">
      <tr>
        <th scope="col" colspan="6">Datos</th>
        <th scope="col" colspan="2">Preocupacional</th>
        <th scope="col" colspan="1"></th>
      </tr>
      <tr>
        <th scope="col">Nombre</th>
        <th scope="col">Apellido</th>
        <th scope="col">DNI</th>
        <th scope="col">Teléfono</th>
        <th scope="col">Nº Legajo</th>
        <th scope="col">Repartición</th>
        <th scope="col">Apto psicológico: </th>
        <th scope="col">Apto médico: </th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      {% for agente in agentes %}
      {% if agente.apto_psi == 1 %}
      {% set apto_psi = 'Si' %}
      {% elif agente.apto_psi == 2 %}
      {% set apto_psi = 'No' %}
      {% else %}
      {% set apto_psi = 'Pendiente' %}
      {% endif %}
      {% if agente.apto_med == 1 %}
      {% set apto_med = 'Si' %}
      {% elif agente.apto_med == 2 %}
      {% set apto_med = 'No' %}
      {% else %}
      {% set apto_med = 'Pendiente' %}
      {% endif %}
      <tr>
        <td>{{ agente.nombre }}</td>
        <td>{{ agente.apellido }}</td>
        <td>{{ agente.dni }}</td>
        <td>{{ agente.telefono or '-' }}</td>
        <td>{{ agente.legajo or '-' }}</td>
        <td>{{ agente.reparticion }}</td>
        <td>{{ apto_psi }}</td>
        <td>{{ apto_med }}</td>
        <td><a class="text-body" href="{{ url_for('preocupacionales.editar_agente', id=agente.id) }}"><i class="fas fa-eye"></i></a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

municipalidad/app/templates/preocupacionales/nuevo_agente.html
{% extends "base.html" %}
{% block extra_head %}
<link rel="stylesheet" href="{{ url_for('static', filename='bootstrap/css/floating-labels.css')}}">
<script src="{{ url_for('static', filename='moment/js/moment.min.js')}}"></script>
<script src="{{ url_for('static', filename='moment/js/locales.js')}}"></script>
<script src="{{ url_for('static', filename='tempusdominus/js/tempusdominus-bootstrap-4.min.js')}}"></script>
<link rel="stylesheet" href="{{ url_for('static', filename='tempusdominus/css/tempusdominus-bootstrap-4.min.css') }}">
<!-- JS datetime pickers -->
<script type="text/javascript">
  $(document).ready(function() {
    $('#turno_psi_1').datetimepicker({
      format: 'DD/MM/YYYY HH:mm',
      locale: 'es',
      stepping: 15
    });
    $('#turno_psi_2').datetimepicker({
      format: 'DD/MM/YYYY HH:mm',
      locale: 'es',
      stepping: 15
    });
    $('#turno_med_1').datetimepicker({
      format: 'DD/MM/YYYY HH:mm',
      locale: 'es',
      stepping: 10
    });
    $('#turno_med_2').datetimepicker({
      format: 'DD/MM/YYYY HH:mm',
      locale: 'es',
      stepping: 10
    });
  });
</script>
{% endblock %}
{% block contenido %}
<!-- Formulario -->
<form action="{{ url_for('preocupacionales.nuevo_agente') }}" method="POST" id="agente" class="needs-validation" novalidate>
  <div class="row">
    <div class="col-md-3"></div><!-- Columna vacía -->
    <div class="col-md-6 border rounded p-3 bg-light">
      {{ form.csrf_token }}
      <div class="row">
        <!-- Area datos -->
        <div class="col-md-12">
          <!-- Datos personales -->
          <div>
            <div class="form-row">
              <div class="form-group col-md-auto h5">
                Datos personales
              </div>
            </div>
            <div class="ml-2">
              <div class="form-row">
                <div class="col-md-6 form-label-group">
                  {% if 'nombre' in form.errors %}
                  {{ form.nombre(autocomplete='off', class='form-control is-invalid', placeholder=form.nombre.name) }}
                  <div class="invalid-tooltip">
                    {{ form.errors['nombre'][0]}}
                  </div>
                  {% else %}
                  {{ form.nombre(autocomplete='off', class='form-control', placeholder=form.nombre.name) }}
                  {% endif %}
                  {{ form.nombre.label }}
                </div>
                <div class="form-label-group col-md-6">
                  {% if 'apellido' in form.errors %}
                  {{ form.apellido(autocomplete='off', class='form-control is-invalid', placeholder=form.apellido.name) }}
                  <div class="invalid-tooltip">
                    {{ form.errors['apellido'][0]}}
                  </div>
                  {% else %}
                  {{ form.apellido(autocomplete='off', class='form-control', placeholder=form.apellido.name) }}
                  {% endif %}
                  {{ form.apellido.label }}
                </div>
              </div>
              <div class="form-row">
                <div class="form-label-group col-md-4">
                  {% if 'dni' in form.errors %}
                  {{ form.dni(autocomplete='off', class='form-control is-invalid', placeholder=form.dni.name) }}
                  <div class="invalid-tooltip">
                    {{ form.errors['dni'][0]}}
                  </div>
                  {% else %}
                  {{ form.dni(autocomplete='off', class='form-control', placeholder=form.dni.name) }}
                  {% endif %}
                  {{ form.dni.label }}
                </div>
                <div class="form-label-group col-md-6">
                  {{ form.telefono(autocomplete='off', class='form-control', placeholder=form.telefono.name) }}
                  {{ form.telefono.label }}
                </div>
              </div>
              <div class="form-row">
                <div class="form-label-group col-md-auto h5">
                  Domicilio
                </div>
              </div>
              <div class="form-row">
                <div class="form-label-group col-md-5">
                  {{ form.domicilio_calle(autocomplete='off', class='form-control', placeholder=form.domicilio_calle.name) }}
                  {{ form.domicilio_calle.label }}
                </div>
                <div class="form-label-group col-md-3">
                  {{ form.domicilio_numero(autocomplete='off', class='form-control', placeholder=form.domicilio_numero.name) }}
                  {{ form.domicilio_numero.label }}
                </div>
              </div>
              <div class="form-row">
                <div class="form-label-group col-md-4">
                  {{ form.domicilio_piso(autocomplete='off', class='form-control', placeholder=form.domicilio_piso.name) }}
                  {{ form.domicilio_piso.label }}
                </div>
                <div class="form-label-group col-md-4">
                  {{ form.domicilio_depto(autocomplete='off', class='form-control', placeholder=form.domicilio_depto.name) }}
                  {{ form.domicilio_depto.label }}
                </div>
              </div>
            </div>
          </div>
          <!-- Fin datos personales -->
          <!-- Datos municipales -->
          <div>
            <div class="form-row">
              <div class="form-group col-md-auto h5">
                Datos municipales
              </div>
            </div>
            <div class="ml-2">
              <div class="form-row">
                <div class="form-label-group col-md-3">
                  {% if 'legajo' in form.errors %}
                  {{ form.legajo(autocomplete='off', class='form-control is-invalid', placeholder=form.legajo.name) }}
                  <div class="invalid-tooltip">
                    {{ form.errors['legajo'][0]}}
                  </div>
                  {% else %}
                  {{ form.legajo(autocomplete='off', class='form-control', placeholder=form.legajo.name) }}
                  {% endif %}
                  {{ form.legajo.label }}
                </div>
                <div class="form-group col-md-9">
                  {% if 'reparticion_id' in form.errors %}
                  {{ form.reparticion_id(autocomplete='off', class='form-control is-invalid') }}
                  <div class="invalid-tooltip">
                    {{ form.errors['reparticion_id'][0]}}
                  </div>
                  {% else %}
                  {{ form.reparticion_id(autocomplete='off', class='form-control') }}
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
          <!-- Fin datos municipales -->
        </div>
        <!-- Fin area datos -->
      </div>
    </div>
    <!-- Fin formulario -->
    <!-- Area botones -->
    <div class="col-md-3">
      <div class="container">
        <div class="row pt-3 justify-content-center">
          <div class="col">
            <div class="btn-block">
              <button form="agente" class="btn btn-primary btn-lg" type="submit" name="buttonGuardar"><i class="fas pr-1 fa-user"></i>Crear agente</button>
            </div>
          </div>
        </div>
      </div>

    </div>
    <!-- Fin area bootnes -->
  </div>
</form>
{% endblock %}